### PR TITLE
build using gradle

### PR DESCRIPTION
**Pull request by x12a1f**
This PR allows ehrservice to be build using a single command. I did the least amount of work to get it to compile so there are no bug fixes etc. The maven build files are also still available.

Major differences between the maven build and this build are:

* Fully self contained build only requiring Java and PostgreSQL with extensions installed.
* Some sources where moved to a different location to match the convention.
* The maven build creates uber/fat jars while the gradle build does not.
* Tests are enabled by default. A few tests are currently disabled because it would take too much time to fix them or they where also broken under maven.
* The database schema is managed by flyway and includes the following changes:
** Extensions are placed in the `ext` schema while all tables are in `ehr`
** All `VARCHAR` fields where replaced with `TEXT` fields (unless the spec defines an exact length). The reason is that our timezone ID `Europe/Amsterdam` was too big to fit in the column. To prevent similar issues in the future I replaced all of them. It should make no difference matter for storage/performance.
** Migrating a database created without flyway to using flyway might be an issue but I suspect dumping the data and then creating the database using flyway would be enough. I did not spend much time on this.
* Removed all generated code, IDE build artifacts, `.svn` directories and other cruft from the repo.
* I only moved the bare minimum of the ripple_patient_summary database scripts/ddl to flyway. 

There are still quite a few ToDo's left but I think this is a good starting point for us to start using ethercis in our services.

### CODE REVIEW

**Comment by ethercis** [comment]
Hi Ralph, could you let us know what artifacts are produced with your gradle build. For example, what are the differences between the gradle generated 'ecis-validation-1.0-SNAPSHOT.jar' and the current one we use in our launch sript? Thanks!

**Comment by x12a1f** [comment]
Currently the only difference is that the jar created by gradle is not a fat/uber jar. As those modules are not intended to be used stand alone, I think it is cleaner to let maven/gradle deal with the dependencies when building the actual application and not including everything in all module jars. 
We had issues with such uber jars before because we needed to use a newer version of a dependency but somehow the classloader picked one from an uber jar. Thats why we prefer not to have uber jars.
Anyway, if needed Gradle can also produce uber jars.

**Comment by x12a1f** [comment]
Hi,

I believe this PR now contains the bare minimum of changes to allow it to be build using Gradle. 

Ralph.

**Comment by ethercis** [comment]
Great stuff, many thanks Ralph!

Re Uber Jar, I agree, this is far from ideal, but a runtime jar containing all dependencies simplifies greatly launch scripts (especially at this stage of the project). Do you have any suggestion for creating, using gradle, something like a 'ethercis-core-runtime.jar' library?

**Pull request merged**
