### PR TITLE
build ehrservice using gradle and removed external dependency on openehr libraries

### PR DESCRIPTION
**Pull request by x12a1f**
I realize this is a huge PR and I don't think it should be accepted as is. At least not before all tests are functioning but we can use this PR for discussion.
See CHANGES.md for more details on the gradle build and the changes made.

Being able to build and test ehrservice using a single command is important for us and we feel this PR is a good step in that direction.

Thanks.

### CODE REVIEW

**Comment by tony-shannon** [comment]
Many thanks @ralphvanetten 

Can you please break down that number of file changes so its a bit easier to digest please?
You might like to link the the list of changes outlined here:
https://github.com/MEDrecord/ehrservice/blob/master/CHANGES.md
eg 	added black box tests (x number of files affected)
with links to example changes

Jan Marc mentioned 2 key issues;
1. about 3000 files are related to "all modifications to the openehr libraries are merged into the openehr directory".. can you explain please

2.  "disabled all code related to ripple-patient-summary" < I'm unclear what you mean by that code, can you provide an example of the issue and how you've dealt with it/how we can refactor 

Anything you can do to make these changes easier to understand and digest please

many thanks
Tony

**Comment by x12a1f** [comment]
I realize this PR is huge and is more for starting discussion than actually accepting the PR as is.
I certainly can split this PR in more manageable pieces. This PR is more a combination of everything I needed to change in order to get it to build.

Currently our main concern is to be able to create reproducible builds without manual intervention which also run all tests.
Once we can do that, we can work on fixing bugs etc. and have a CI checking our work.

I had some difficulties in building ehrservice using the provided maven build so I added a gradle build to it. (Gradle just because we're used to it, but it can be maven also)

More manageable steps would be:

* update the build system to it can build using a single command
* get all tests working
* remove the depencencies to the binary only openehr libraries
* start fixing some bugs

But in order to do that I would like some feedback on some issues like

* How do you guys feel about switching from maven to gradle for building? Either one is fine for us although we prefer gradle because we have more positive experiences with it.
* How do you feel about using flyway to manage the database schemas? This makes database migrations much easier, also for deployment on servers.

The goal here is to run a single command on a fresh machine and then be able to build and run all tests.

As for the other issues you mentioned:

1. ehrservice uses https://github.com/openEHR/java-libs version 1.0.9 with some modifications made to it. I was unable to find the sources for these libraries and version 1.0.9 also was pulled from the various maven repositories on the internet. To avoid running opensource software for which no sources are available, we decompiled the 1.0.9 library and applied all changes we've found to the official openehr sources. The majority of the changes in this PR comes from this. Including those changes in this PR was the quickest solution but there are better solutions available. I also mentioned this in https://github.com/ethercis/ethercis/issues/14
2. When the ripple-patient-summary module added some changes to the database schema where also made as I mentioned in https://github.com/ethercis/ethercis/issues/15 Some classes in ehrservice depend on the database schema changes which makes it impossible to generate the database sources and compile ehrservice without including the ripple-patient-summary. I would have expected for everything related to ripple to live in their own repository independent from ehrservice.

I do appreciate all the work you all have put into ethercis and I do recognize the complexity and the soundness of the design behind all it.

I will start working on more manageable PRs but I will need some feedback as mentioned above.

Thanks,
Ralph.

**Comment by tony-shannon** [comment]
Many thanks Ralph,
Thats very helpful , appreciate your help and support and I'm beginning to understand your issues better now.
In short answer to the Q you share;

*How do you guys feel about switching from maven to gradle for building? Either one is fine for us although we prefer gradle because we have more positive experiences with it.*
Am more familiar with maven than gradle but whatever yourself and Christian agree is fine by me.
Are you saying that both could be running the builds in parallel, so we offer others who join this effort the choice? If so sounds like a win-win.. assuming there is little/no down side.

*How do you feel about using flyway to manage the database schemas? This makes database migrations much easier, also for deployment on servers.*
Sounds like a good idea, assume we could/should unless lots of effort, (it appears straightforward). 
Hope Christian likes this idea/ he may have an alternative.

*"The goal here is to run a single command on a fresh machine and then be able to build and run all tests"* = good goal

*Re: ehrservice uses https://github.com/openEHR/java-libs version 1.0.9 with some modifications made to it*
https://github.com/ethercis/ethercis/issues/14
You outline 2 options.. 
We need Christian to explain his rationale for "modifications .. made to the (openEHR) reference implementation"
Either way the fork of openEHR ref implementation or new set of modules make some sense to me.
Christian will guide us on the preferred route.

*re  "ripple-patient-summary to be a separate module in its own repo so ehrservice will function and can be build without the ripple-patient-summary. "*
Agree in principle, we dont want any application specific code in EtherCIS, I need to understand this aspect of the code better but a seperate module sounds sensible. Christian will guide on the generic/ deeper issue here and guide on the way we resolve this one.

Thanks again
Tony

**Comment by x12a1f** [comment]
**Maven vs Gradle:**
I think it is best to just pick one. I did some research and I think I'm able to do everything with maven as well. We also used maven in the past but as the projects grew bigger and more complex, maven became much more difficult to use. If there is the possibility to use gradle I believe it would simplify the build but in the end it does not matter much.

**ripple-patient-summary**
In https://github.com/ethercis/ethercis/issues/15 Christian explained it a bit. It seems the module can be used in a more generic way than its name implies.

**Comment by tony-shannon** [comment]
thanks @ralphvanetten 

This is something Id hope yourself and Christian can discuss, I'd like to know the pros/cons

As with all things technical I can already find 2 alternate views;
https://gradle.org/maven-vs-gradle
http://softwareyoga.com/10-reasons-why-we-chose-maven-over-gradle/

If it doesnt matter too much then there may be an argument for sticking with Maven for now.
Please do feel free to make the case for Gradle here if you like, I'm always keen to be educated and hear differing views..and will be happy to contribute to the decision

thanks
Tony

**Comment by x12a1f** [comment]
Hi @tony-shannon,

Regarding maven vs gradle: I can tell you only about our experiences: we used to have maven builds but as soon as the projects became more complex (building debian packages, database migrations, generating swagger documentation, passing build variables to the continuous integration system) maven became much more difficult to use and we ended up writing our own maven plugins and (platform dependent) helper scripts.
I'm sure everything can also be done in maven but for us using gradle was less effort, cleaner and everything could be nicely integrated with gradle (although gradle does have a bit of a learning curve but their documentation is very good) 
For simple projects following convention it does not matter much though.

**Comment by tony-shannon** [comment]
thanks @ralphvanetten that's interesting.
Am guessing this may be a recurrent issue as other folk want to join the effort.
We need a stable path I guess and take care in choosing the right tool at the right time.
Suggest we discuss on conference call tomorrow.
Tony

**Comment by x12a1f** [comment]
as discussed I will resubmit this PR as multiple smaller PRs

**Pull request closed without merging**
